Prod dev proj
sintsovamy/wspace pull request #1
Opened 2023-10-17 17:05 UTC by sintsovamy

2023-10-17 23:57 UTC, RetmixX requested changes
Поправить замечания и снова на проверку

2023-10-17 23:57 UTC, RetmixX commented on dev/.dockerignore
> +.git
Эта папка по умолчанию не пушится и не отслеживается

2023-10-17 23:57 UTC, RetmixX commented on dev/.env.example
Переменные не должны быть заполнены

2023-10-17 23:57 UTC, RetmixX commented on dev/docker-compose.yml
> +    image: php:8.1-fpm
Существует образ на основе alpine
php:8.1-fpm-alpine

2023-10-17 23:57 UTC, RetmixX commented on prod/ws_nginx/ws_nginx.conf.prod
> +	server_name 127.0.0.1;
Тут можно просто localhost оставить

2023-10-17 23:57 UTC, RetmixX commented on prod/ws_nginx/files/index.html
Оп, выпилваем фронт

2023-10-17 23:57 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
В проде волюмы убираем, у тебя есть докерфайлы там и копируй из системы в докер

2023-10-17 23:57 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
Этот волюм можешь оставить, так как если навернется база, то и данные тоже потеряются, что будет очень печально

2023-10-17 23:57 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
В докерфайл образа пхп вынеси перенос исходного кода

2023-10-17 23:57 UTC, RetmixX commented on prod/.env.example
Так же почистить, у тебя рабочей версией является .env, которым ты сама пользуешься

2023-10-17 23:57 UTC, RetmixX commented on dev/ws_nginx/ws_nginx.conf.prod
По имени файл относится к проду, но он в деве. Поправь

2023-10-17 23:57 UTC, RetmixX commented on dev/ws_nginx/ws_nginx.conf.prod
> +	server_name 127.0.0.1;
Так же лучше локалхост сюда запихать

2023-10-17 23:57 UTC, RetmixX commented on dev/php/Dockerfile
Либо используй Dockerfile в деве, либо удаляй, как ненужный файл

2023-10-18 01:49 UTC, jurapro requested changes
Согласен с замечаниями Андрея. Можно еще порты админера закрыть которые на внешку смотрят, а доступ к нему через прокси организовать

2023-10-18 09:41 UTC, acferten requested changes
Тебе остался последний рывок 🤕🤕

2023-10-18 09:41 UTC, acferten commented on dev/.env.example
Описать переменные в README

2023-10-18 09:41 UTC, acferten commented on dev/docker-compose.yml
>      ports:
Порты убрать, в прокси должно по url /adminer перекидывать на сервис (контейнер) adminer'а. Подсказка: см. proxy_pass: service:port

2023-10-18 09:41 UTC, acferten commented on dev/php/Dockerfile
> +WORKDIR /var/www/html
Почему html, если в контейнерах прокси и пхп волюм  ../project:/var/www/

2023-10-18 09:41 UTC, acferten commented on prod/php/Dockerfile
> +WORKDIR /var/www/html
то же самое. кто такой html?? мы на беке таким не занимаемся 😳😳😳😳

2023-10-18 09:41 UTC, acferten commented on prod/ws_nginx/ws_nginx.conf.prod
> +	server_name localhost;
вынести в переменную окружения. на проде у тебя явно будет не локалхост, а какой-то домен

2023-10-18 14:56 UTC, jurapro approved these changes
Приемлимо вполне, только исправь ошибки которые ребята написали. Делай курс по PHP используя это окружение

2023-10-19 02:09 UTC, RetmixX approved these changes
Good work

2023-11-03 15:23 UTC, merged